### ISSUE TITLE
Assignment within conditional

### ISSUE THREAD

**Issue by iszard** [greensock/GreenSock-AS3#10]
Just downloaded what I'm assuming was the latest zip build from the greensock site. Once I uploaded into Flash Builder, it was quick to point out that in the file

TweenPlugin.as  : com.greensock.plugins

Line 285 : if ((pt._prev = pt2 ? pt2._prev : last)) {
Line 290 : if ((pt._next = pt2)) {

Should the ='s not be doubled? ==

**Comment by jackdoyle** [comment]
Nope, that's perfectly valid code and it's very purposeful. It is a speed and file size optimization. Flash Builder is just assuming that we probably meant == since it's a common mistake. That's why it's a "warning", not an "error". 

To be clear, this:
if ((pt._next = pt2)) {

Is the same as this:
pt._next = pt2;
if (pt._next !== null) {

**Comment by iszard** [comment]
thanks for the clarification.
